//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabber_Insights.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>Goal Title 1</string>
  <string>Goal Title 2</string>
  <string>Goal Title 3</string>
  <string>Goal Title 4</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TabberGoalTitles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TabberGoalTitles"]));
            }
            set {
                this["TabberGoalTitles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>6 January 2023</string>
  <string>6 January 2023</string>
  <string>6 January 2023</string>
  <string>6 January 2023</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TabberGoalDates {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TabberGoalDates"]));
            }
            set {
                this["TabberGoalDates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>0%</string>
  <string>0%</string>
  <string>0%</string>
  <string>0%</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TabberGoalPriorities {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TabberGoalPriorities"]));
            }
            set {
                this["TabberGoalPriorities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>Goal Description 1</string>
  <string>Goal Description 2</string>
  <string>Goal Description 3</string>
  <string>Goal Description 4</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TabberGoalDescriptions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TabberGoalDescriptions"]));
            }
            set {
                this["TabberGoalDescriptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int FocusPeriodMinutes {
            get {
                return ((int)(this["FocusPeriodMinutes"]));
            }
            set {
                this["FocusPeriodMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int BreakPeriodMinutes {
            get {
                return ((int)(this["BreakPeriodMinutes"]));
            }
            set {
                this["BreakPeriodMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReflectionLogs {
            get {
                return ((string)(this["ReflectionLogs"]));
            }
            set {
                this["ReflectionLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int ReflectionScore {
            get {
                return ((int)(this["ReflectionScore"]));
            }
            set {
                this["ReflectionScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastReflectionLog {
            get {
                return ((string)(this["LastReflectionLog"]));
            }
            set {
                this["LastReflectionLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalFocusSeconds {
            get {
                return ((int)(this["TotalFocusSeconds"]));
            }
            set {
                this["TotalFocusSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApplicationVersion {
            get {
                return ((string)(this["ApplicationVersion"]));
            }
            set {
                this["ApplicationVersion"] = value;
            }
        }
    }
}
